-- ⚠️ SUPERSEDED / DO NOT APPLY — historical only.
-- The booking system was consolidated into the Crescent Car Reports Supabase
-- project (ref jwslaqufrdoodsxasxnr); its schema is now owned by THAT repo's
-- migrations 006_bookings.sql + 007_simplify_booking_statuses.sql. This file is
-- the OLD website-owned model (different booking_status values: pending_confirmation
-- / confirmed / completed) and is no longer applied to the shared database.
-- Kept for history; do not run it against any project.

create table if not exists bookings (
  -- Human-friendly reference generated by the API (e.g. CCC-LXY3-AB12) and shown
  -- to the customer on the confirmation page, so it doubles as the primary key.
  id                       text primary key,
  created_at               timestamptz default now() not null,
  updated_at               timestamptz default now() not null,

  customer_name            text not null,
  customer_phone           text not null,
  customer_email           text,

  emirate                  text not null,
  address                  text not null,
  location_lat             double precision,
  location_lng             double precision,
  parking_type             text not null check (parking_type in ('showroom', 'outdoor', 'home')),
  additional_notes         text,

  car_make                 text not null,
  car_model                text not null,
  car_year                 text not null,

  -- Preferred date + window only; the exact arrival time is confirmed later.
  preferred_date           date not null,
  preferred_window         text not null check (preferred_window in ('morning', 'afternoon', 'evening')),

  package_id               text not null,
  package_name             text not null,
  -- Base package price, the flat travel surcharge (0 for near emirates), and the
  -- total the customer pays (package_price + travel_fee). The amount Stripe
  -- charges is total_price.
  package_price            integer not null,
  travel_fee               integer not null default 0,
  total_price              integer not null,

  -- Stripe Checkout. The session id is set right after the hold is created; the
  -- payment intent id is filled by the webhook once payment succeeds.
  stripe_session_id        text unique,
  stripe_payment_intent_id text,

  payment_status           text not null default 'pending'
    check (payment_status in ('pending', 'paid', 'failed', 'refunded')),
  booking_status           text not null default 'pending_payment'
    check (booking_status in ('pending_payment', 'pending_confirmation', 'confirmed', 'cancelled', 'completed')),

  -- A new booking is a temporary payment hold: it occupies its date/window until
  -- hold_expires_at (now + 20 min). After that, expireOldHolds() releases it.
  hold_expires_at          timestamptz,
  paid_at                  timestamptz,
  cancelled_at             timestamptz,

  -- Filled when a tentative Google Calendar hold is created after payment.
  google_calendar_event_id text
);

create index if not exists bookings_payment_status_idx on bookings(payment_status);
create index if not exists bookings_booking_status_idx on bookings(booking_status);
create index if not exists bookings_preferred_date_idx on bookings(preferred_date);
create index if not exists bookings_slot_idx          on bookings(preferred_date, preferred_window);
create index if not exists bookings_hold_expires_idx  on bookings(hold_expires_at) where hold_expires_at is not null;
create index if not exists bookings_created_at_idx    on bookings(created_at desc);
create index if not exists bookings_stripe_session_idx on bookings(stripe_session_id) where stripe_session_id is not null;

-- Database-level guarantee that a single date/window can only be held by ONE
-- active booking at a time: either a paid (pending_confirmation/confirmed)
-- booking, or a live payment hold (pending_payment/pending). Expired holds are
-- flipped to cancelled/failed by expireOldHolds() before each availability check
-- and insert, so they leave this index and free the slot. A concurrent second
-- insert for the same slot therefore fails with a unique violation (23505),
-- which the API turns into a 409.
create unique index if not exists bookings_active_slot_idx
  on bookings (preferred_date, preferred_window)
  where (payment_status = 'paid' and booking_status in ('pending_confirmation', 'confirmed'))
     or (payment_status = 'pending' and booking_status = 'pending_payment');

alter table bookings enable row level security;
-- Service role bypasses RLS; this denies everyone else (anon/auth) all access.
drop policy if exists "Service role only" on bookings;
create policy "Service role only" on bookings using (false) with check (false);

-- Contact-form messages, saved before the owner notification email is sent so a
-- message is never lost if email delivery fails.
create table if not exists contact_messages (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz default now() not null,
  name        text not null,
  email       text not null,
  phone       text,
  topic       text,
  car_make    text,
  car_model   text,
  car_year    text,
  message     text not null
);

create index if not exists contact_messages_created_at_idx on contact_messages(created_at desc);

alter table contact_messages enable row level security;
drop policy if exists "Service role only" on contact_messages;
create policy "Service role only" on contact_messages using (false) with check (false);
